export const weatherMap = new Map([
  ['01d', 'assets/images/clear-sky-day.jpg'],
  ['01n', 'assets/images/clear-sky-night.jpg'],
  ['02d', 'assets/images/few-clouds-day.jpg'],
  ['02n', 'assets/images/cloud-night.jpg'],
  ['03d', 'assets/images/few-clouds-day.jpg'],
  ['03n', 'assets/images/cloud-night.jpg'],
  ['04d', 'assets/images/few-clouds-day.jpg'],
  ['04n', 'assets/images/cloud-night.jpg'],
  ['09d', 'assets/images/rain-day.jpg'],
  ['09n', 'assets/images/rain-night.jpg'],
  ['10d', 'assets/images/rain-day.jpg'],
  ['10n', 'assets/images/rain-night.jpg'],
  ['11d', 'assets/images/thunderstorm.png'],
  ['11n', 'assets/images/thunderstorm.png'],
  ['13d', 'assets/images/snow.jpg'],
  ['13n', 'assets/images/snow.jpg'],
  ['50d', 'assets/images/mist.jpg'],
  ['50n', 'assets/images/mist.jpg'],
]);
